#!/usr/bin/env bash
# Shebang line
clear
# Alias to the commit command

# git commit -m "git remote and remote_maker" -m "substring extraction" -m "pattern matching continues"
s=""
m_tag=""
for i in "${@}"
	do
	# echo "$i"
	if [ "${i:0:1}" = "-" ] && [[ "$i" = *m* ]] && (( "${#i}" < 6 )) &&
			[ ! "${i:0:2}" = "--" ]
		then
		m_tag="$i" # If -m flag is pesent, then record it
		s="$s $i"
	else
		s="$s \"$i\""
	fi
	done


if [ -z "$m_tag" ] # If no -m flag given
	then
	if [ -n "$s" ]; then s="-m $s" # if we have message text, simply add the flag
	else # Message text does not exist either, reuse the last message
		s=" -C HEAD"
	fi
fi
# echo "$s"
eval "git commit $s"
# Done

# c -m "msg 4 1" -m "msg 4 2" -m "msg 4 3"
# c -m "The msg here"
