#!/usr/bin/env bash
# Shebang line
clear
# Alias to the commit command

# Git fn: checks if arg contains the -m flag as in -am or -m, etc
function has_m_flag()
{
	[[ "$1" == -* && "$1" == *m* && "$1" != --* ]] && return 0
	return 1
}

# git commit -m "git remote and remote_maker" -m "substring extraction" -m "pattern matching continues"
s=""
m_tag=""
for i in "${@}"
	do
	if has_m_flag "$i" # If -m flag is pesent, then record it
		then
		m_tag="$i"
		s="$s $i"
	else # This is the actual string message
		s="$s \"$i\""
	fi
	done

if [[ -n "$m_tag" && -z "$s" ]] # If there's -m flag but message is missing
	then
	echo "commit message missing"
	exit 1
fi

if [[ -z "$m_tag" && -z "$s" ]] # If both -m flag and message are missing
	then
	# Message text does not exist either, reuse the last message
	eval "git commit -C HEAD"
	exit 0
fi

# If the first param doesn't contain -m flag but we have a message, add it
if ! has_m_flag $1 && [[ -n "$s" ]] # Is there message
	then
	s="-m $s"
fi

eval "git commit $s"

# c -m "msg 4 1" -m "msg 4 2" -m "msg 4 3"
# c "The msg here"
# c The msg here
