#!/bin/bash

clear
comp_args=()
args=("$@")
index=0

# Loop though command arguments and
# filter out c files into the array com_args
# remove the c file from the command arguments
# At last, args will only contain arguments meant for the program
for arg in "${args[@]}"; do
  if [[ $arg == *.c ]]; then
    comp_args+=("$arg")
    unset "args[$index]"
  fi
  ((index++))
done


# call compile with c files and
# call program with program arguments
compile "${comp_args[@]}" -o a.out
./a.out "${args[@]}"
