#!/usr/bin/bash
# Reset the BMM system service
clear
cd /home/michaeliyke/michaeliyke/projects/BMM || exit
sudo cp bmm.service /etc/systemd/system/bmm.service
sudo systemctl daemon-reload
sudo systemctl restart bmm.service
sudo systemctl status bmm.service
