#!/bin/bash

clear
comp_args=()
args=("$@")
index=0
compile_status=0

# Loop though command arguments and
# filter out c files into the array com_args
# remove the c file from the command arguments
# At last, args will only contain arguments meant for the program
for arg in "${args[@]}"; do
  if [[ $arg == *.c ]]; then
    comp_args+=("$arg")
    unset "args[$index]"
  fi
  ((index++))
done


# call compile with c files and
# call program with program arguments
# gcc -Wall -Wextra -pedantic -Werror -std=gnu89 -g "${comp_args[@]}" -o a.out
gcc -Wall -Wextra -Werror -pedantic -std=gnu89 "${comp_args[@]}" -lm -o a.out
# Execute compiled prgram only if compilation was successful
compile_status=$(echo $?)

if (( $compile_status != 0 )); then
	echo
	echo "Compilation failed!"
	echo
	exit $compile_status
fi

# echo "Build successful!"
# echo
./a.out "${args[@]}"
