#!/usr/bin/env bash
# Create a new virtual environment for the project in current directory
# Usage: createnv [env_name]
# If no env_name is provided, it will use the project name as the env_name
# If the virtual environment already exists, it won't be recreated

# Get the project name
project_name=$(basename "$(pwd)")

# Get the virtual environment name
env_name=${1:-$project_name}

# Change of plan. Default env_name is now 'env'
env_name=${1:-env}

# Check if the virtual environment already exists
if [ -d "$env_name" ]; then
	echo "Virtual environment '$env_name' already exists"
	exit 1
fi

# Create the virtual environment
python3 -m venv "$env_name"

echo "Virtual environment '$env_name' created"

# Create the conditional variable for the .gitignore file
# If the .gitignore file is in the parent directory, use that instead
gitignore=".gitignore"
if [ -f "../.gitignore" ]; then
	gitignore="../.gitignore"
fi

# If the .gitignore file doesn't exist, create it
if [ ! -f "$gitignore" ]; then
	touch "$gitignore"
	echo "Created .gitignore file in current directory"
fi

# grep -qE "^v?(env)$" .gitignore || echo "env" >> .gitignore
# Adding the env directory to .gitignore if not exists
if ! grep -q "^${env_name}$" "$gitignore"; then
	echo "$env_name" >> "$gitignore"
	echo "Added '$env_name' to the .gitignore file"
else
	echo "'$env_name' already exists in the .gitignore file"
fi

# Make a hard link to the activate script in current directory
ln "$env_name/bin/activate" activate
echo "Created hard link 'activate' in current directory"
