#!/usr/bin/env bash
sudo mysql -p hbnb_dev_db < truc.sql # execute the trunc.sql file
sudo mysql -p hbnb_dev_db < states.sql # Autopopulate the states table data
sudo mysql -p -D hbnb_dev_db -e "describe cities"
sudo mysql -p -D hbnb_dev_db