#!/usr/bin/env bash
# https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04

# Gain super user root access
# This is the one used
sudo mysql

# Below is the one used most often but only gains admin privileges
# mysql -u root -p

# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
# ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;
# sudo systemctl restart mysql
# sudo systemctl start mysql
# sudo systemctl stop mysql
# sudo systemctl status mysql
# CREATE USER 'username'@'host' IDENTIFIED WITH authentication_plugin BY 'password';
# GRANT PRIVILEGE ON database.table TO 'username'@'host';
# GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT, REFERENCES, RELOAD
# on *.* TO 'sammy'@'localhost' WITH GRANT OPTION;
# GRANT ALL PRIVILEGES ON *.* TO 'sammy'@'localhost' WITH GRANT OPTION;
# FLUSH PRIVILEGES;