#!/usr/bin/env bash
# https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04

# Gain super user root access
# This is the one used
sudo mysql

# Below is the one used most often but only gains admin privileges
# mysql -u root -p

# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
# ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;
# sudo systemctl restart mysql
# sudo systemctl start mysql
# sudo systemctl stop mysql
# sudo systemctl status mysql
# CREATE USER 'username'@'host' IDENTIFIED WITH authentication_plugin BY 'password';
# GRANT PRIVILEGE ON database.table TO 'username'@'host';
# GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT, REFERENCES, RELOAD
# on *.* TO 'sammy'@'localhost' WITH GRANT OPTION;
# GRANT ALL PRIVILEGES ON *.* TO 'sammy'@'localhost' WITH GRANT OPTION;
# FLUSH PRIVILEGES;
# GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost'
CREATE TABLE nexus6 ( id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
insert into nexus6 (name) values("Leon");
create database if not exists tyrell_corp;
CREATE USER 'Ann'@'localhost' IDENTIFIED WITH my_custom_auth BY 'abc';
CREATE USER 'holberton_user'@'localhost' IDENTIFIED WITH authentication_plugin BY 'projectcorrection280hbtn';
CREATE TABLE nexus6 ( id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));

 GRANT SELECT on tyrell_corp.nexus6 TO 'holberton_user'@'localhost' WITH GRANT OPTION;

 sudo mysql -p -e "show create table hbnb_dev_db.states"