#!/usr/bin/env bash
#+ Run a local script against a remote machine.
#+ You must have been able to connect with this remote earlier

#+ Examples
#+ run_on_remote web02 ~/bin/install_regular.sh
#+ run_on_remote ubuntu@54.237.104.249 configure.sh 

REMOTE=$1
TASK=$2
ssh "$REMOTE" "'$TASK'"


