#!/usr/bin/bash
# This script is used to check the logs of the bmm service
# The -f option is used to follow the logs
# and display new logs as they are written

# Get process name
process="$1"

if  [ $# -eq 0 ]; then
	# Show all processes
	ps aux
	exit 0
else
	# Show all instances of the process such as gunicorn
	# shellcheck disable=SC2009
	ps aux | grep "$process"
	# pgrep -f "$process" > /dev/null
		exit 0
fi
