#!/usr/bin/env bash
# LIST ALL FILES IN CURRENT DIRECTORY
# IF EXTENSION IS PROVIDED THEN ALL OF FILES OF THAT TYPE IS LISTED

# check there is more than one parameters and warn with correct usage
if (( $# > 1 ))
	then
	echo "Usage: ${0##*/} extension"
	exit 1
fi

# assign ext to parameter 1 or null
ext="$1"

# Loop through all files in current directory
if [ -n "$ext" ]
	then # List all files of the given extension type

	for f in *
		do
		if [ -f "$f" ] && [ "$ext" = "${f#*.}" ]
			then
			echo "$f"
		fi
	done

else # No extension given so list all files

	for f in *
		do
		if [ -f "$f" ]
			then
			echo "$f"
		fi
	done

fi
